#!/usr/bin/env python3
"""Compile the dev/CI toolchain into hash-pinned requirements files.

    python3 scripts/lock_toolchain.py            # regenerate requirements/*.txt
    python3 scripts/lock_toolchain.py --check     # fail (exit 1) on drift
    python3 scripts/lock_toolchain.py --upgrade   # re-resolve to newest allowed

Each ``requirements/<name>.in`` is the human-edited declaration; the generated
``requirements/<name>.txt`` beside it carries an exact version *and every
artifact's sha256* for the full transitive closure. pip enforces those hashes
automatically (any hash in a requirements file implies ``--require-hashes``), so
a yanked, re-uploaded or compromised transitive dependency fails the install
instead of silently changing a build.

The ``--check`` form runs in CI's lint job and in ``make lint``, exactly like
``build_registries.py --check`` / ``build_roadmap.py --check``: the generated
file is committed, and a stale one is a red gate rather than a surprise later.

Why hash-pinned requirements rather than ``uv.lock``:

* ``[project].dependencies`` is empty and must stay that way — boost's runtime
  is stdlib-only. A ``uv.lock`` wants the dev tools declared *in* pyproject.toml,
  which would put dev tooling in the shipped metadata.
* A universal ``uv.lock`` would also materialize the ``[eval]`` extra's
  deliberately-old langchain 0.3 stack (pinned because ragas 0.2.x needs it) into
  a committed, scannable file. ``.github/workflows/osv-scanner.yml`` is
  PR-diff-scoped specifically to avoid tripping on that pin; a lockfile would
  re-expose it. The ``[eval]`` extra is intentionally absent here.
* ``pip install -r`` needs no extra tool at install time, which matters on the
  3 OS x 3 Python test matrix. uv is needed only to *regenerate*.

Groups are per-consumer and self-contained on purpose. pip enforces hashes
across the whole resolution, so two independently-compiled files that pin the
same transitive dependency to different versions cannot be installed together —
``mutation-tools.in`` redeclares the test tools via ``-r`` instead of layering.
"""
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REQS = ROOT / "requirements"

# (stem, python-version) for each group. Every group resolves --universal.
#
# Universal is not optional for a *committed* lock. Without it uv resolves for
# the machine it runs on, so a file generated on macOS omits the Linux-only
# artifacts CI needs — the drift check then fails on the runner while passing
# locally, which is exactly what happened first time round (release-tools came
# back STALE on CI). Universal emits environment markers instead, so one file is
# correct everywhere and byte-identical no matter who regenerates it.
#
# `python_version` is the interpreter the group's CI job pins, and it matters:
# refurb needs >=3.10 and mutmut >=3.11, so neither can resolve at the 3.9
# floor. Only `test-tools` resolves from 3.9 — it is the one set that installs on
# every leg of the 3 OS x 3 Python matrix, and the markers let one file give 3.9
# the last release that supported it while 3.12/3.14 still get the current one.
GROUPS = (
    ("lint-tools", "3.12"),
    ("test-tools", "3.9"),
    ("mutation-tools", "3.11"),
    ("coverage-tools", "3.12"),
    ("release-tools", "3.12"),
)

# uv stamps the invoking command (including absolute paths and the -o target)
# into a header comment, which would differ between a developer's machine and
# the CI runner and break a byte-exact drift check. Replace it with a stable
# header naming this script instead.
_UV_HEADER = re.compile(r"\A# This file was autogenerated by uv[^\n]*\n"
                        r"(?:#[^\n]*\n)*")


def _header(stem: str, python_version: str) -> str:
    """The stable, machine-independent banner for a generated file."""
    return (
        "# GENERATED by scripts/lock_toolchain.py — DO NOT EDIT.\n"
        "#\n"
        "# Edit requirements/%s.in, then run:\n"
        "#     python3 scripts/lock_toolchain.py\n"
        "#\n"
        "# Resolved universally from Python %s — environment markers cover every\n"
        "# OS and interpreter, so this file is byte-identical wherever it is\n"
        "# regenerated. Every artifact is sha256-pinned, and pip enforces those\n"
        "# hashes on install (any hash implies --require-hashes), so a yanked or\n"
        "# tampered transitive dependency fails the install instead of silently\n"
        "# changing the build.\n"
        % (stem, python_version)
    )


def _uv() -> str:
    """Path to a usable uv, preferring the repo venv's."""
    local = ROOT / ".venv" / "bin" / "uv"
    return str(local) if local.exists() else (shutil.which("uv") or "uv")


def compile_group(stem: str, python_version: str, upgrade: bool) -> str:
    """Resolve one group and return the file contents we want on disk.

    Resolution is deliberately NOT "newest that satisfies the .in". uv treats an
    existing ``--output-file`` as the preferred solution and keeps those pins
    unless a declaration forces a change, so the compile is *stable*: it
    reproduces the committed lock byte-for-byte until someone edits the .in or
    passes ``--upgrade``.

    That distinction is the whole gate. Compiling to stdout instead re-resolves
    against the live index every time, so any upstream release makes the
    committed lock "stale" and reddens `lint` on unrelated PRs with no code
    change — which is precisely the failure mode requirements/lint-tools.in's
    header was written about. (It happened: three groups went STALE overnight.)
    """
    target = REQS / ("%s.txt" % stem)
    # Compile into a scratch copy of the committed lock so uv can read the
    # current pins and prefer them, without touching the real file until the
    # caller decides to write it.
    with tempfile.TemporaryDirectory() as tmp:
        scratch = Path(tmp) / target.name
        if target.exists():
            shutil.copyfile(target, scratch)
        cmd = [_uv(), "pip", "compile", str(REQS / ("%s.in" % stem)),
               "--generate-hashes", "--universal",
               "--python-version", python_version, "--no-header",
               "--output-file", str(scratch)]
        if upgrade:
            cmd.append("--upgrade")
        proc = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
        if proc.returncode != 0:
            sys.stderr.write(proc.stderr)
            raise SystemExit("lock_toolchain: `uv pip compile` failed for %s" % stem)
        body = _UV_HEADER.sub("", scratch.read_text(encoding="utf-8")).lstrip("\n")
    return _header(stem, python_version) + body


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any generated file is stale")
    ap.add_argument("--upgrade", action="store_true",
                    help="re-resolve to the newest versions the .in files allow")
    args = ap.parse_args()

    if args.check and args.upgrade:
        raise SystemExit("lock_toolchain: --check and --upgrade are exclusive")

    stale = []
    for stem, python_version in GROUPS:
        target = REQS / ("%s.txt" % stem)
        want = compile_group(stem, python_version, args.upgrade)
        if args.check:
            have = target.read_text(encoding="utf-8") if target.exists() else ""
            if have != want:
                stale.append(stem)
            continue
        target.write_text(want, encoding="utf-8")
        print("wrote %s" % target.relative_to(ROOT))

    if args.check:
        if stale:
            print("toolchain lock is STALE for: %s" % ", ".join(stale))
            print("run `python3 scripts/lock_toolchain.py` and commit the result")
            return 1
        print("toolchain lock is up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
