"""Render a boost skill into another agent framework's native source.

boost installs skills as files for editor-style agents (Claude Code, Cursor,
Windsurf). Frameworks like CrewAI or the OpenAI Agents SDK are *application
code* — they have no skills directory to install into; an agent is a value
constructed in a Python source file. `boost adapt <name> --to <framework>`
bridges that gap by emitting the framework's own idiom.

Each renderer is a pure, deterministic string transform: (name, description,
body) -> valid Python source. No framework is imported here — the emitted text
is a template, so the stdlib-only, zero-dependency runtime contract holds. The
generated code's *validity* is what the tests pin (it must `compile()`); whether
a given framework version accepts the kwargs is verified out-of-gate, with that
framework installed.
"""
from __future__ import annotations

import json
import keyword
import re
from typing import Callable, Dict, List, Optional

# Public: the format id shown in `--to`/errors -> its renderer.
# Populated at the bottom once the render_* functions are defined.
FORMATS: Dict[str, "Callable[..., str]"] = {}


def formats() -> List[str]:
    """Sorted list of supported target framework ids (for help/errors)."""
    return sorted(FORMATS)


def render(fmt: str, name: str, description: str, body: str,
           model: Optional[str] = None) -> str:
    """Dispatch to the renderer for `fmt`. Raises KeyError on unknown fmt.

    `model` (a boost/LiteLLM model id) wires the emitted agent to a specific
    LLM; when falsy the agent inherits its framework's default provider. The
    command layer turns a KeyError into a BoostError listing formats().
    """
    return FORMATS[fmt](name, description, body, model)


# --- shared helpers -------------------------------------------------------

def _py_str(s: str) -> str:
    """A safely-escaped Python string literal for ANY input.

    JSON string syntax is a subset of Python's, so json.dumps yields a literal
    that is valid Python too — quotes, backslashes and newlines all escaped —
    with ensure_ascii=False keeping non-ASCII readable (and still valid). This
    is the whole defense against a skill body that contains quotes or `\"\"\"`.
    """
    return json.dumps(s, ensure_ascii=False)


def _ident(name: str) -> str:
    """A safe Python identifier derived from a skill name.

    `code-reviewer` -> `code_reviewer`; leading digits or a Python keyword get
    an `s_` prefix so the emitted assignment target always parses.
    """
    ident = re.sub(r"\W+", "_", name.strip().lower()).strip("_")
    if not ident or ident[0].isdigit() or keyword.iskeyword(ident):
        ident = "s_" + ident
    return ident


def _clean(text: str) -> str:
    """Collapse trailing whitespace so emitted literals stay tidy."""
    return text.strip()


def _litellm_model(model: str) -> str:
    """Normalize a boost model id to a LiteLLM `provider/model` string.

    boost's AI bridge is Anthropic (the `claude` CLI / Anthropic API), so a bare
    Claude id like `claude-haiku-4-5-20251001` gets an `anthropic/` prefix.
    A value that already names a provider (`anthropic/…`, `openai/gpt-4o`) is
    passed through unchanged. Both CrewAI and the Agents SDK route through
    LiteLLM, so this one form serves both.
    """
    m = model.strip()
    return m if "/" in m else "anthropic/" + m


# --- renderers ------------------------------------------------------------

def render_crewai(name: str, description: str, body: str,
                  model: Optional[str] = None) -> str:
    """A CrewAI Agent: role=name, goal=description, backstory=instructions.

    With `model`, pins the agent's LLM via `crewai.LLM` (LiteLLM under the
    hood); without it, the agent uses CrewAI's default provider.
    """
    var = _ident(name)
    imports = "from crewai import Agent\n"
    llm = ""
    if model:
        imports = "from crewai import Agent, LLM\n"
        llm = "    llm=LLM(model=%s),\n" % _py_str(_litellm_model(model))
    return (
        "# Generated by `boost adapt %s --to crewai`. Do not edit by hand.\n"
        "%s"
        "\n"
        "%s = Agent(\n"
        "    role=%s,\n"
        "    goal=%s,\n"
        "    backstory=%s,\n"
        "%s"
        ")\n"
    ) % (
        name,
        imports,
        var,
        _py_str(name),
        _py_str(_clean(description)),
        _py_str(_clean(body)),
        llm,
    )


def render_agents_sdk(name: str, description: str, body: str,
                      model: Optional[str] = None) -> str:
    """An OpenAI Agents SDK Agent: instructions carry the skill body.

    With `model`, pins the agent's LLM via the SDK's LiteLLM extension
    (`pip install "openai-agents[litellm]"`); without it, the agent uses the
    SDK's default OpenAI model.
    """
    var = _ident(name)
    imports = "from agents import Agent\n"
    llm = ""
    if model:
        imports = ("from agents import Agent\n"
                   "from agents.extensions.models.litellm_model import LitellmModel\n")
        llm = "    model=LitellmModel(model=%s),\n" % _py_str(_litellm_model(model))
    return (
        "# Generated by `boost adapt %s --to agents-sdk`. Do not edit by hand.\n"
        "%s"
        "\n"
        "%s = Agent(\n"
        "    name=%s,\n"
        "    handoff_description=%s,\n"
        "    instructions=%s,\n"
        "%s"
        ")\n"
    ) % (
        name,
        imports,
        var,
        _py_str(name),
        _py_str(_clean(description)),
        _py_str(_clean(body)),
        llm,
    )


FORMATS.update({
    "crewai": render_crewai,
    "agents-sdk": render_agents_sdk,
})
