# Copyright the boost contributors.
# SPDX-License-Identifier: Apache-2.0
"""``docs/vex/openvex.json`` — boost's OpenVEX 0.2.0 feed — round-trips and
stays fresh.

The document is generated by ``scripts/build_vex.py`` from one Markdown
statement file per finding under ``docs/vex/statements/`` (the same
frontmatter-plus-body convention ``scripts/build_roadmap.py`` uses for
``docs/roadmap/items/*.md``, so parallel loops adding statements don't collide
on one shared file). This is the in-suite twin of the
``build_vex.py --check`` CI step, plus a schema check against the fields
OpenVEX (and OSPS-VM-04.02) actually require: ``@context``, ``@id``,
``author``, ``timestamp``, ``version``, and each statement's ``vulnerability``,
``products``, ``status``, and — whenever ``status`` is ``not_affected`` — a
``justification``.

Skips when the repo-root files aren't reachable (e.g. the mutation sandbox,
which only copies ``boost_cli/``).
"""
from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parents[2]
_SCRIPT = _ROOT / "scripts" / "build_vex.py"
_VEX_DIR = _ROOT / "docs" / "vex"
_STATEMENTS = _VEX_DIR / "statements"
_META = _VEX_DIR / "meta.md"
_OUTPUT = _VEX_DIR / "openvex.json"

_reachable = _SCRIPT.exists() and _STATEMENTS.exists() and _META.exists()
_skip = pytest.mark.skipif(
    not _reachable, reason="repo-root files not reachable (e.g. mutation sandbox)")

_JUSTIFICATIONS = (
    "component_not_present",
    "vulnerable_code_not_present",
    "vulnerable_code_not_in_execute_path",
    "vulnerable_code_cannot_be_controlled_by_adversary",
    "inline_mitigations_already_exist",
)


def _load_builder():
    spec = importlib.util.spec_from_file_location("build_vex", _SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# --------------------------------------------------------------------------- #
# Freshness — the committed docs/vex/openvex.json matches a fresh render     #
# --------------------------------------------------------------------------- #
@_skip
def test_openvex_json_is_regenerated():
    builder = _load_builder()
    committed = _OUTPUT.read_text(encoding="utf-8")
    assert committed == builder.build(), (
        "docs/vex/openvex.json is stale — regenerate with\n"
        "    python3 scripts/build_vex.py\n"
        "and commit the result (see CONTRIBUTING.md)."
    )


@_skip
def test_check_flag_passes_on_fresh_tree():
    builder = _load_builder()
    assert builder.main(["--check"]) == 0


@_skip
def test_check_flag_fails_when_output_is_stale(tmp_path, monkeypatch):
    builder = _load_builder()
    stale = tmp_path / "openvex.json"
    stale.write_text('{"stale": true}\n', encoding="utf-8")
    monkeypatch.setattr(builder, "OUTPUT_FILE", stale)
    assert builder.main(["--check"]) == 1


# --------------------------------------------------------------------------- #
# Schema — required OpenVEX fields, read off the real generated document     #
# --------------------------------------------------------------------------- #
@_skip
class TestOpenVexSchema:
    @staticmethod
    @pytest.fixture(scope="class")
    def doc():
        return json.loads(_load_builder().build())

    def test_top_level_required_fields(self, doc):
        for field in ("@context", "@id", "author", "timestamp", "version", "statements"):
            assert field in doc, "missing required OpenVEX field %r" % field

    def test_context_is_openvex_0_2_0(self, doc):
        assert doc["@context"] == "https://openvex.dev/ns/v0.2.0"

    def test_id_is_a_stable_url(self, doc):
        assert doc["@id"].startswith("https://")
        assert doc["@id"].endswith("openvex.json")

    def test_author_is_non_empty(self, doc):
        assert isinstance(doc["author"], str) and doc["author"].strip()

    def test_timestamp_parses_as_iso8601(self, doc):
        from datetime import datetime
        # fromisoformat needs "+00:00" rather than a bare "Z" before 3.11;
        # boost's floor is 3.12, but normalise anyway rather than assume.
        datetime.fromisoformat(doc["timestamp"].replace("Z", "+00:00"))

    def test_version_is_a_positive_integer(self, doc):
        assert isinstance(doc["version"], int) and doc["version"] >= 1

    def test_at_least_one_statement(self, doc):
        # An empty-but-schema-valid document would still pass every field
        # check below; this is what stops "no statements" from being silently
        # acceptable when real, sourced findings exist to describe.
        assert doc["statements"], "no statements — see docs/vex/statements/"

    def test_every_statement_has_required_fields(self, doc):
        for stmt in doc["statements"]:
            for field in ("vulnerability", "products", "status"):
                assert field in stmt, "statement missing %r: %r" % (field, stmt)

    def test_vulnerability_carries_a_name(self, doc):
        for stmt in doc["statements"]:
            assert stmt["vulnerability"].get("name"), stmt

    def test_products_is_a_non_empty_list_of_identified_components(self, doc):
        for stmt in doc["statements"]:
            products = stmt["products"]
            assert products and isinstance(products, list)
            for product in products:
                assert product.get("@id"), product

    def test_status_is_a_valid_openvex_status(self, doc):
        valid = {"not_affected", "affected", "fixed", "under_investigation"}
        for stmt in doc["statements"]:
            assert stmt["status"] in valid, stmt["status"]

    def test_not_affected_statements_carry_a_justification(self, doc):
        for stmt in doc["statements"]:
            if stmt["status"] == "not_affected":
                assert stmt.get("justification") in _JUSTIFICATIONS, stmt

    def test_no_fabricated_cve_identifiers(self, doc):
        """The task this document exists for is explicit: no invented CVEs.

        Every vulnerability named here must trace to a real, committed
        suppression (a CodeQL inline ``# codeql[...]`` comment, the gitleaks
        allowlist, a ``.github/zizmor.yml`` ignore) rather than a fabricated
        CVE/GHSA identifier — pin the shape rather than trust it stays true.
        """
        for stmt in doc["statements"]:
            name = stmt["vulnerability"]["name"]
            assert not name.upper().startswith("CVE-"), name
            assert not name.upper().startswith("GHSA-"), name


# --------------------------------------------------------------------------- #
# Statement source files — every one is well-formed on its own terms        #
# --------------------------------------------------------------------------- #
@_skip
class TestStatementSourceFiles:
    def test_every_statement_file_is_named_for_its_id(self):
        bad = []
        for path in sorted(_STATEMENTS.glob("*.md")):
            builder = _load_builder()
            meta, _ = builder.frontmatter.parse(path.read_text(encoding="utf-8"))
            if meta.get("id") != path.stem:
                bad.append("%s declares id %r" % (path.name, meta.get("id")))
        assert not bad, "; ".join(bad)

    def test_every_statement_has_a_sourced_impact_statement(self):
        builder = _load_builder()
        for item in builder.load_statements():
            assert item["_body"], "%s: empty impact statement" % item["_file"]


# --------------------------------------------------------------------------- #
# Loader/renderer behaviour — exercised against synthetic files, not the    #
# committed set, so a bad statement is caught before it can merge.          #
# --------------------------------------------------------------------------- #
@_skip
class TestLoaderValidation:
    def _write(self, tmp_path, name, text):
        stmts = tmp_path / "statements"
        stmts.mkdir(exist_ok=True)
        (stmts / name).write_text(text, encoding="utf-8")
        return stmts

    def test_missing_id_is_rejected(self, tmp_path, monkeypatch):
        builder = _load_builder()
        stmts = self._write(tmp_path, "x.md", "---\nvulnerability: t:x\nstatus: not_affected\njustification: vulnerable_code_not_present\n---\nbecause reasons\n")
        monkeypatch.setattr(builder, "STATEMENTS_DIR", stmts)
        with pytest.raises(builder.VexError, match="missing 'id'"):
            builder.load_statements()

    def test_filename_id_mismatch_is_rejected(self, tmp_path, monkeypatch):
        builder = _load_builder()
        stmts = self._write(tmp_path, "x.md", "---\nid: y\nvulnerability: t:x\nstatus: not_affected\njustification: vulnerable_code_not_present\n---\nbecause reasons\n")
        monkeypatch.setattr(builder, "STATEMENTS_DIR", stmts)
        with pytest.raises(builder.VexError, match="does not match filename"):
            builder.load_statements()

    def test_missing_vulnerability_is_rejected(self, tmp_path, monkeypatch):
        builder = _load_builder()
        stmts = self._write(tmp_path, "x.md", "---\nid: x\nstatus: not_affected\njustification: vulnerable_code_not_present\n---\nbecause reasons\n")
        monkeypatch.setattr(builder, "STATEMENTS_DIR", stmts)
        with pytest.raises(builder.VexError, match="missing 'vulnerability'"):
            builder.load_statements()

    def test_unknown_status_is_rejected(self, tmp_path, monkeypatch):
        builder = _load_builder()
        stmts = self._write(tmp_path, "x.md", "---\nid: x\nvulnerability: t:x\nstatus: not_a_real_status\n---\nbecause reasons\n")
        monkeypatch.setattr(builder, "STATEMENTS_DIR", stmts)
        with pytest.raises(builder.VexError, match="bad status"):
            builder.load_statements()

    def test_not_affected_without_justification_is_rejected(self, tmp_path, monkeypatch):
        builder = _load_builder()
        stmts = self._write(tmp_path, "x.md", "---\nid: x\nvulnerability: t:x\nstatus: not_affected\n---\nbecause reasons\n")
        monkeypatch.setattr(builder, "STATEMENTS_DIR", stmts)
        with pytest.raises(builder.VexError, match="justification"):
            builder.load_statements()

    def test_empty_impact_statement_is_rejected(self, tmp_path, monkeypatch):
        builder = _load_builder()
        stmts = self._write(tmp_path, "x.md", "---\nid: x\nvulnerability: t:x\nstatus: not_affected\njustification: vulnerable_code_not_present\n---\n")
        monkeypatch.setattr(builder, "STATEMENTS_DIR", stmts)
        with pytest.raises(builder.VexError, match="empty"):
            builder.load_statements()

    def test_affected_status_does_not_require_justification(self, tmp_path, monkeypatch):
        # not required by the spec, but must not be *rejected* either — some
        # future finding may legitimately be `affected` or `under_investigation`.
        builder = _load_builder()
        stmts = self._write(tmp_path, "x.md", "---\nid: x\nvulnerability: t:x\nstatus: under_investigation\n---\nstill triaging\n")
        monkeypatch.setattr(builder, "STATEMENTS_DIR", stmts)
        items = builder.load_statements()
        assert len(items) == 1

    def test_default_product_is_the_pypi_purl_when_unset(self, tmp_path, monkeypatch):
        builder = _load_builder()
        stmts = self._write(tmp_path, "x.md", "---\nid: x\nvulnerability: t:x\nstatus: not_affected\njustification: vulnerable_code_not_present\n---\nbecause reasons\n")
        monkeypatch.setattr(builder, "STATEMENTS_DIR", stmts)
        [item] = builder.load_statements()
        stmt = builder.render_statement(item)
        assert stmt["products"] == [{"@id": builder.DEFAULT_PRODUCT}]

    def test_statements_render_sorted_by_id(self, tmp_path, monkeypatch):
        builder = _load_builder()
        stmts = tmp_path / "statements"
        stmts.mkdir()
        for sid in ("zzz", "aaa", "mmm"):
            (stmts / ("%s.md" % sid)).write_text(
                "---\nid: %s\nvulnerability: t:x\nstatus: not_affected\n"
                "justification: vulnerable_code_not_present\n---\nreason\n" % sid,
                encoding="utf-8")
        monkeypatch.setattr(builder, "STATEMENTS_DIR", stmts)
        ids = [item["id"] for item in builder.load_statements()]
        assert ids == ["aaa", "mmm", "zzz"]
