# Copyright the boost contributors.
# SPDX-License-Identifier: GPL-3.0-only
"""Unit tests for core.adapters — the framework export renderers.

These are mutation-gated: assertions pin exact emitted structure and prove the
output is valid Python, so any template mutation (dropped field, swapped kwarg,
broken escaping) fails a test.
"""
import ast
from typing import ClassVar

import pytest

from boost_cli.core import adapters


class TestFormats:
    def test_registry_lists_all_frameworks(self):
        assert adapters.formats() == ["agents-sdk", "crewai", "langgraph"]

    def test_formats_is_sorted(self):
        assert adapters.formats() == sorted(adapters.formats())

    def test_render_dispatches_by_id(self):
        crew = adapters.render("crewai", "x", "d", "b")
        sdk = adapters.render("agents-sdk", "x", "d", "b")
        assert "from crewai import Agent" in crew
        assert "from agents import Agent" in sdk

    def test_render_unknown_raises_keyerror(self):
        with pytest.raises(KeyError):
            adapters.render("langchain", "x", "d", "b")


class TestPyStr:
    def test_plain(self):
        assert adapters._py_str("hi") == '"hi"'

    def test_escapes_quotes(self):
        assert adapters._py_str('say "hi"') == '"say \\"hi\\""'

    def test_escapes_newlines(self):
        assert adapters._py_str("a\nb") == '"a\\nb"'

    def test_escapes_backslash(self):
        assert adapters._py_str("a\\b") == '"a\\\\b"'

    def test_non_ascii_stays_readable(self):
        # ensure_ascii=False: the é survives literally, not as é.
        assert adapters._py_str("café") == '"café"'

    @pytest.mark.parametrize("s", ["", '"""', 'a"b\'c\\d\ne', "tab\there", "🚀"])
    def test_result_is_a_valid_python_literal_evaluating_back(self, s):
        lit = adapters._py_str(s)
        assert ast.literal_eval(lit) == s


class TestIdent:
    def test_hyphen_to_underscore(self):
        assert adapters._ident("code-reviewer") == "code_reviewer"

    def test_spaces_and_case(self):
        assert adapters._ident("My Cool Skill") == "my_cool_skill"

    def test_strips_punctuation(self):
        assert adapters._ident("a.b/c!") == "a_b_c"

    def test_leading_digit_prefixed(self):
        assert adapters._ident("3d-tools") == "s_3d_tools"

    def test_python_keyword_prefixed(self):
        assert adapters._ident("class") == "s_class"

    def test_empty_prefixed(self):
        assert adapters._ident("!!!") == "s_"

    def test_result_is_always_a_valid_identifier(self):
        for name in ["code-reviewer", "3d", "class", "!!!", "a b c", "def"]:
            assert adapters._ident(name).isidentifier()


class TestClean:
    def test_strips_surrounding_whitespace(self):
        assert adapters._clean("  hi \n") == "hi"


class TestRenderCrewai:
    def setup_method(self):
        self.src = adapters.render_crewai(
            "code-reviewer",
            "Reviews a diff for correctness",
            "Review the diff.\nRank by severity.",
        )

    def test_is_valid_python(self):
        compile(self.src, "<crewai>", "exec")

    def test_imports_crewai_agent(self):
        assert "from crewai import Agent" in self.src

    def test_assigns_to_identifier_from_name(self):
        assert "code_reviewer = Agent(" in self.src

    def test_role_is_name(self):
        assert 'role="code-reviewer"' in self.src

    def test_goal_is_description(self):
        assert 'goal="Reviews a diff for correctness"' in self.src

    def test_backstory_carries_body(self):
        assert 'backstory="Review the diff.\\nRank by severity."' in self.src

    def test_has_provenance_header(self):
        assert self.src.startswith(
            "# Generated by `boost adapt code-reviewer --to crewai`.")

    def test_exact_output(self):
        assert self.src == (
            "# Generated by `boost adapt code-reviewer --to crewai`."
            " Do not edit by hand.\n"
            "from crewai import Agent\n"
            "\n"
            "code_reviewer = Agent(\n"
            '    role="code-reviewer",\n'
            '    goal="Reviews a diff for correctness",\n'
            '    backstory="Review the diff.\\nRank by severity.",\n'
            ")\n"
        )


class TestRenderAgentsSdk:
    def setup_method(self):
        self.src = adapters.render_agents_sdk(
            "triage", "Routes questions", "You are a triage agent.")

    def test_is_valid_python(self):
        compile(self.src, "<sdk>", "exec")

    def test_imports_agents_agent(self):
        assert "from agents import Agent" in self.src

    def test_name_kwarg(self):
        assert 'name="triage"' in self.src

    def test_handoff_description_is_description(self):
        assert 'handoff_description="Routes questions"' in self.src

    def test_instructions_carry_body(self):
        assert 'instructions="You are a triage agent."' in self.src

    def test_exact_output(self):
        assert self.src == (
            "# Generated by `boost adapt triage --to agents-sdk`."
            " Do not edit by hand.\n"
            "from agents import Agent\n"
            "\n"
            "triage = Agent(\n"
            '    name="triage",\n'
            '    handoff_description="Routes questions",\n'
            '    instructions="You are a triage agent.",\n'
            ")\n"
        )


class TestRenderLanggraph:
    def setup_method(self):
        self.src = adapters.render_langgraph(
            "code-reviewer",
            "Reviews a diff for correctness",
            "Review the diff.\nRank by severity.",
        )

    def test_is_valid_python(self):
        compile(self.src, "<langgraph>", "exec")

    def test_imports_create_react_agent(self):
        assert "from langgraph.prebuilt import create_react_agent" in self.src

    def test_emits_a_node_factory_named_from_skill(self):
        assert "def make_code_reviewer(model, tools=None):" in self.src

    def test_body_is_the_system_prompt(self):
        assert 'SYSTEM_PROMPT = "Review the diff.\\nRank by severity."' in self.src

    def test_factory_binds_prompt_and_tools(self):
        assert ("return create_react_agent(model, tools=tools or [], "
                "prompt=SYSTEM_PROMPT)") in self.src

    def test_has_provenance_header(self):
        assert self.src.startswith(
            "# Generated by `boost adapt code-reviewer --to langgraph`.")

    def test_exact_output(self):
        assert self.src == (
            "# Generated by `boost adapt code-reviewer --to langgraph`."
            " Do not edit by hand.\n"
            "from langgraph.prebuilt import create_react_agent\n"
            "\n"
            'SYSTEM_PROMPT = "Review the diff.\\nRank by severity."\n'
            "\n"
            "\n"
            "def make_code_reviewer(model, tools=None):\n"
            '    "Reviews a diff for correctness"\n'
            "    return create_react_agent(model, tools=tools or [],"
            " prompt=SYSTEM_PROMPT)\n"
        )


class TestLanggraphWithModel:
    def setup_method(self):
        self.src = adapters.render_langgraph(
            "code-reviewer", "Reviews a diff", "Review it.",
            "claude-haiku-4-5-20251001")

    def test_is_valid_python(self):
        compile(self.src, "<lg>", "exec")

    def test_model_defaults_the_factory_arg(self):
        # LangChain init_chat_model wants provider:model (colon), not litellm's slash.
        assert ('def make_code_reviewer('
                'model="anthropic:claude-haiku-4-5-20251001", tools=None):'
                in self.src)

    def test_exact_output(self):
        assert self.src == (
            "# Generated by `boost adapt code-reviewer --to langgraph`."
            " Do not edit by hand.\n"
            "from langgraph.prebuilt import create_react_agent\n"
            "\n"
            'SYSTEM_PROMPT = "Review it."\n'
            "\n"
            "\n"
            'def make_code_reviewer('
            'model="anthropic:claude-haiku-4-5-20251001", tools=None):\n'
            '    "Reviews a diff"\n'
            "    return create_react_agent(model, tools=tools or [],"
            " prompt=SYSTEM_PROMPT)\n"
        )


class TestAdversarialBodiesStayValid:
    """A skill body full of quote/escape hazards must still emit valid Python."""

    HAZARDS: ClassVar[list] = [
        'has "double" and \'single\' quotes',
        'triple """ quotes """ inside',
        "trailing backslash \\",
        "newlines\nand\ttabs",
        "unicode → café 🚀 ↯",
        "",
    ]

    @pytest.mark.parametrize("body", HAZARDS)
    def test_crewai_compiles(self, body):
        compile(adapters.render_crewai("s", "d", body), "<c>", "exec")

    @pytest.mark.parametrize("body", HAZARDS)
    def test_agents_sdk_compiles(self, body):
        compile(adapters.render_agents_sdk("s", "d", body), "<c>", "exec")

    @pytest.mark.parametrize("body", HAZARDS)
    def test_langgraph_compiles(self, body):
        compile(adapters.render_langgraph("s", "d", body), "<c>", "exec")

    def test_body_round_trips_through_the_literal(self):
        # Extract the backstory literal and confirm it decodes to the original.
        body = 'weird """ body with "quotes" and \\ slashes\nand lines'
        src = adapters.render_crewai("s", "d", body)
        tree = ast.parse(src)
        call = tree.body[-1].value  # the Agent(...) call
        backstory = next(k.value for k in call.keywords if k.arg == "backstory")
        assert ast.literal_eval(backstory) == body


class TestLitellmModel:
    def test_bare_id_gets_anthropic_prefix(self):
        assert adapters._litellm_model("claude-haiku-4-5-20251001") == \
            "anthropic/claude-haiku-4-5-20251001"

    def test_provider_qualified_passes_through(self):
        assert adapters._litellm_model("anthropic/claude-sonnet-5") == \
            "anthropic/claude-sonnet-5"
        assert adapters._litellm_model("openai/gpt-4o") == "openai/gpt-4o"

    def test_strips_whitespace(self):
        assert adapters._litellm_model("  claude-x  ") == "anthropic/claude-x"


class TestLangchainModel:
    def test_bare_id_gets_anthropic_colon(self):
        assert adapters._langchain_model("claude-haiku-4-5-20251001") == \
            "anthropic:claude-haiku-4-5-20251001"

    def test_litellm_slash_becomes_colon(self):
        assert adapters._langchain_model("anthropic/claude-sonnet-5") == \
            "anthropic:claude-sonnet-5"
        assert adapters._langchain_model("openai/gpt-4o") == "openai:gpt-4o"

    def test_colon_form_passes_through(self):
        assert adapters._langchain_model("anthropic:claude-x") == "anthropic:claude-x"

    def test_strips_whitespace(self):
        assert adapters._langchain_model("  claude-x  ") == "anthropic:claude-x"


class TestCrewaiWithModel:
    def setup_method(self):
        self.src = adapters.render_crewai(
            "code-reviewer", "Reviews a diff", "Review it.",
            "claude-haiku-4-5-20251001")

    def test_is_valid_python(self):
        compile(self.src, "<c>", "exec")

    def test_imports_llm_alongside_agent(self):
        assert "from crewai import Agent, LLM" in self.src

    def test_wires_llm_kwarg_with_normalized_model(self):
        assert 'llm=LLM(model="anthropic/claude-haiku-4-5-20251001")' in self.src

    def test_exact_output(self):
        assert self.src == (
            "# Generated by `boost adapt code-reviewer --to crewai`."
            " Do not edit by hand.\n"
            "from crewai import Agent, LLM\n"
            "\n"
            "code_reviewer = Agent(\n"
            '    role="code-reviewer",\n'
            '    goal="Reviews a diff",\n'
            '    backstory="Review it.",\n'
            '    llm=LLM(model="anthropic/claude-haiku-4-5-20251001"),\n'
            ")\n"
        )


class TestAgentsSdkWithModel:
    def setup_method(self):
        self.src = adapters.render_agents_sdk(
            "triage", "Routes questions", "You are a triage agent.",
            "anthropic/claude-sonnet-5")

    def test_is_valid_python(self):
        compile(self.src, "<c>", "exec")

    def test_imports_litellm_model_extension(self):
        assert ("from agents.extensions.models.litellm_model import LitellmModel"
                in self.src)

    def test_wires_model_kwarg(self):
        assert 'model=LitellmModel(model="anthropic/claude-sonnet-5")' in self.src

    def test_exact_output(self):
        assert self.src == (
            "# Generated by `boost adapt triage --to agents-sdk`."
            " Do not edit by hand.\n"
            "from agents import Agent\n"
            "from agents.extensions.models.litellm_model import LitellmModel\n"
            "\n"
            "triage = Agent(\n"
            '    name="triage",\n'
            '    handoff_description="Routes questions",\n'
            '    instructions="You are a triage agent.",\n'
            '    model=LitellmModel(model="anthropic/claude-sonnet-5"),\n'
            ")\n"
        )


class TestModelOmittedIsUnchanged:
    """model=None (the opt-out) must reproduce the original framework-default
    output byte-for-byte — no LLM import, no llm/model kwarg."""

    def test_crewai_no_llm_when_model_none(self):
        src = adapters.render_crewai("x", "d", "b", None)
        assert "LLM" not in src
        assert "llm=" not in src
        assert src == adapters.render_crewai("x", "d", "b")

    def test_agents_sdk_no_model_when_none(self):
        src = adapters.render_agents_sdk("x", "d", "b", None)
        assert "LitellmModel" not in src
        assert "model=" not in src
        assert src == adapters.render_agents_sdk("x", "d", "b")

    def test_empty_model_is_treated_as_omitted(self):
        # falsy model ("") must not emit an LLM line
        assert "LLM" not in adapters.render_crewai("x", "d", "b", "")

    @pytest.mark.parametrize("fmt", ["crewai", "agents-sdk", "langgraph"])
    def test_render_dispatch_passes_model_through(self, fmt):
        src = adapters.render(fmt, "x", "d", "b", "claude-x")
        # crewai/agents-sdk emit litellm anthropic/claude-x; langgraph emits the
        # LangChain anthropic:claude-x — either way the model is wired through.
        assert "claude-x" in src and "anthropic" in src
        compile(src, "<c>", "exec")

    @pytest.mark.parametrize("fmt", ["crewai", "agents-sdk", "langgraph"])
    def test_model_output_still_compiles(self, fmt):
        compile(adapters.render(fmt, "s", "d", 'body """ x', "claude-y"),
                "<c>", "exec")
