# Copyright the boost contributors.
# SPDX-License-Identifier: Apache-2.0
"""Unit tests: core/adapters.render_runner — the `boost run` runner script.

The runner is generated text that must ``compile()`` and carry the adapted
agent (brain) + the default toolset (hands) + a Runner call. No framework is
imported — validity is compilation, exactly like the other adapters.
"""
from __future__ import annotations

import sys
import types

import pytest

from boost_cli.core import adapters


def _runner(**kw):
    kw.setdefault("name", "code-reviewer")
    kw.setdefault("description", "Reviews code for bugs")
    kw.setdefault("body", "You are a precise code reviewer.")
    return adapters.render_runner(**kw)


def test_runner_compiles():
    compile(_runner(model="claude-haiku-4-5-20251001", target="target.py"),
            "<runner>", "exec")


def test_runner_embeds_the_adapted_agent_brain():
    src = _runner()
    assert "Agent(" in src
    assert "instructions=" in src           # the skill body becomes instructions
    assert "You are a precise code reviewer." in src


def test_runner_wires_the_default_toolset():
    src = _runner()
    for tool in ("def read_file(", "def list_dir(", "def grep("):
        assert tool in src
    assert "tools=[read_file, list_dir, grep]" in src


def test_runner_calls_the_runner_on_the_agent():
    src = _runner()
    assert "run_sync(" in src
    assert "final_output" in src


def test_runner_with_model_pins_litellm():
    src = _runner(model="claude-haiku-4-5-20251001")
    assert "LitellmModel" in src
    assert "anthropic/claude-haiku-4-5-20251001" in src


def test_runner_without_model_has_no_litellm():
    src = _runner(model=None)
    assert "LitellmModel" not in src


def test_runner_target_appears_in_the_prompt():
    src = _runner(target="src/app.py")
    assert "`src/app.py`" in src


def test_runner_without_target_points_at_cwd():
    src = _runner(target=None)
    assert "current directory" in src


def test_runner_escapes_a_hostile_target_and_body():
    # quotes, a newline, a percent and a backtick must not break compilation
    src = _runner(body='body "q"\nline2 100% \\ done',
                  target='weird"\n%s`name')
    compile(src, "<hostile>", "exec")


def test_runner_reuses_render_agents_sdk_header():
    # the brain half is exactly render_agents_sdk output, header and all
    src = _runner(model=None, target="x")
    assert "--to agents-sdk" in src
    assert src.startswith("# Generated by")


# ── executing the runner against a stub SDK (proves it actually runs) ──────

@pytest.fixture()
def stub_agents_sdk(monkeypatch):
    """Install a faithful-enough stub of `openai-agents` so the generated runner
    can be exec()'d offline — Agent records its kwargs, function_tool wraps a
    function (NOT an Agent), Runner reports the wired agent."""
    m = types.ModuleType("agents")

    class Agent:
        def __init__(self, name=None, instructions=None, model=None, tools=None, **kw):
            self.name, self.instructions = name, instructions
            self.model, self.tools = model, tools or []

    class _FunctionTool:
        def __init__(self, fn):
            self.name = fn.__name__

    class Runner:
        @staticmethod
        def run_sync(agent, prompt):
            return types.SimpleNamespace(
                final_output="[ran %s / %d tools]" % (agent.name, len(agent.tools)))

    m.Agent, m.function_tool, m.Runner = Agent, _FunctionTool, Runner
    lm = types.ModuleType("agents.extensions.models.litellm_model")
    lm.LitellmModel = lambda model=None: types.SimpleNamespace(model=model)
    mods = {
        "agents": m,
        "agents.extensions": types.ModuleType("agents.extensions"),
        "agents.extensions.models": types.ModuleType("agents.extensions.models"),
        "agents.extensions.models.litellm_model": lm,
    }
    for name, mod in mods.items():
        monkeypatch.setitem(sys.modules, name, mod)
    return Agent


def _exec_runner(src):
    ns: dict = {}
    exec(compile(src, "<runner>", "exec"), ns)  # noqa: S102  (running the generated runner is the point)
    return ns


def test_generated_runner_actually_runs(stub_agents_sdk):
    ns = _exec_runner(_runner(model="claude-haiku-4-5-20251001", target="t.py"))
    agent = ns["_boost_agent"]
    assert isinstance(agent, stub_agents_sdk)
    assert [t.name for t in agent.tools] == ["read_file", "list_dir", "grep"]


@pytest.mark.parametrize("name", ["grep", "read-file", "list-dir", "read_file"])
def test_runner_survives_a_skill_named_after_a_tool(stub_agents_sdk, name):
    # the skill name normalizes onto a tool identifier; the brain must still be
    # captured (not clobbered by the tool def) so the runner does not crash.
    ns = _exec_runner(adapters.render_runner(name, "d", "You do things.",
                                             model=None, target="x"))
    assert ns["_boost_agent"].name == name
    assert len(ns["_boost_agent"].tools) == 3
