"""Unit tests: core/adapters.render_runner — the `boost run` runner script.

The runner is generated text that must ``compile()`` and carry the adapted
agent (brain) + the default toolset (hands) + a Runner call. No framework is
imported — validity is compilation, exactly like the other adapters.
"""
from __future__ import annotations

from boost_cli.core import adapters


def _runner(**kw):
    kw.setdefault("name", "code-reviewer")
    kw.setdefault("description", "Reviews code for bugs")
    kw.setdefault("body", "You are a precise code reviewer.")
    return adapters.render_runner(**kw)


def test_runner_compiles():
    compile(_runner(model="claude-haiku-4-5-20251001", target="target.py"),
            "<runner>", "exec")


def test_runner_embeds_the_adapted_agent_brain():
    src = _runner()
    assert "Agent(" in src
    assert "instructions=" in src           # the skill body becomes instructions
    assert "You are a precise code reviewer." in src


def test_runner_wires_the_default_toolset():
    src = _runner()
    for tool in ("def read_file(", "def list_dir(", "def grep("):
        assert tool in src
    assert "tools=[read_file, list_dir, grep]" in src


def test_runner_calls_the_runner_on_the_agent():
    src = _runner()
    assert "run_sync(" in src
    assert "final_output" in src


def test_runner_with_model_pins_litellm():
    src = _runner(model="claude-haiku-4-5-20251001")
    assert "LitellmModel" in src
    assert "anthropic/claude-haiku-4-5-20251001" in src


def test_runner_without_model_has_no_litellm():
    src = _runner(model=None)
    assert "LitellmModel" not in src


def test_runner_target_appears_in_the_prompt():
    src = _runner(target="src/app.py")
    assert "`src/app.py`" in src


def test_runner_without_target_points_at_cwd():
    src = _runner(target=None)
    assert "current directory" in src


def test_runner_escapes_a_hostile_target_and_body():
    # quotes, a newline, a percent and a backtick must not break compilation
    src = _runner(body='body "q"\nline2 100% \\ done',
                  target='weird"\n%s`name')
    compile(src, "<hostile>", "exec")


def test_runner_reuses_render_agents_sdk_header():
    # the brain half is exactly render_agents_sdk output, header and all
    src = _runner(model=None, target="x")
    assert "--to agents-sdk" in src
    assert src.startswith("# Generated by")
