"""Unit tests: the hash-pinned dev/CI toolchain (requirements/*.txt).

These assert the lock's *invariants* rather than its contents — a version bump
must not need a test edit, but the properties that make the lock worth having
(every requirement pinned, every pin hashed, every consumer's file present) must
never silently erode.

The freshness check itself (`scripts/lock_toolchain.py --check`) is not run here:
it needs `uv` and the network. `make lint` and CI's lint job own that.
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
REQS = ROOT / "requirements"

# Every group scripts/lock_toolchain.py generates, and the consumer that reads
# it. Keep in step with that script's GROUPS tuple.
GROUPS = ("lint-tools", "test-tools", "mutation-tools", "coverage-tools",
          "release-tools")

_REQ = re.compile(r"^(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)"
                  r"(?P<spec>==[^\s;\\]+)?(?P<rest>.*)$")


def _clean(raw):
    """A compiled line with its line-continuation backslash removed."""
    return raw.strip().rstrip("\\").strip()


def _requirement_lines(text):
    """The requirement lines of a compiled file (no comments, no hash lines)."""
    lines = []
    for raw in text.splitlines():
        line = _clean(raw)
        if not line or line.startswith("#") or line.startswith("-"):
            continue                           # comment, --hash, -r, --index-url
        lines.append(line)
    return lines


def _blocks(text):
    """(requirement line, [hashes]) for each requirement in a compiled file."""
    out = []
    current = None
    for raw in text.splitlines():
        line = _clean(raw)
        if not line or line.startswith("#"):
            continue
        if line.startswith("--hash="):
            if current is not None:
                current[1].append(line)
            continue
        if line.startswith("-"):
            continue
        current = (line, [])
        out.append(current)
    return out


class TestEveryGroupIsLocked:
    def test_declaration_exists_for_every_group(self):
        for stem in GROUPS:
            assert (REQS / ("%s.in" % stem)).is_file(), stem

    def test_generated_lock_exists_for_every_group(self):
        for stem in GROUPS:
            assert (REQS / ("%s.txt" % stem)).is_file(), stem

    def test_no_stray_generated_file_without_a_declaration(self):
        # a .txt with no .in would be hand-maintained — exactly what the
        # generator exists to replace.
        for txt in REQS.glob("*.txt"):
            assert (REQS / (txt.stem + ".in")).is_file(), txt.name

    def test_lock_toolchain_groups_match_this_test(self):
        # the script is the source of truth; this pins them together so adding a
        # group there without locking it here is a failure, not a silent gap.
        src = (ROOT / "scripts" / "lock_toolchain.py").read_text(encoding="utf-8")
        for stem in GROUPS:
            assert '"%s"' % stem in src, stem


class TestLockInvariants:
    def test_every_requirement_is_pinned_exactly(self):
        for stem in GROUPS:
            text = (REQS / ("%s.txt" % stem)).read_text(encoding="utf-8")
            for line in _requirement_lines(text):
                m = _REQ.match(line.strip())
                assert m, "unparseable requirement in %s: %r" % (stem, line)
                assert m.group("spec"), \
                    "%s is not pinned with == in %s" % (m.group("name"), stem)

    def test_every_pin_carries_hashes(self):
        # This is the whole point: pip implies --require-hashes when any hash is
        # present, so a single unhashed requirement would break the install
        # rather than weaken it — but a file with NO hashes installs happily and
        # silently gives up the guarantee.
        for stem in GROUPS:
            text = (REQS / ("%s.txt" % stem)).read_text(encoding="utf-8")
            blocks = _blocks(text)
            assert blocks, "%s has no requirements at all" % stem
            for line, hashes in blocks:
                assert hashes, "%s: %r carries no --hash" % (stem, line)
                for h in hashes:
                    assert re.fullmatch(r"--hash=sha256:[0-9a-f]{64}", h), \
                        "%s: malformed hash %r" % (stem, h)

    def test_generated_files_are_marked_generated(self):
        for stem in GROUPS:
            head = (REQS / ("%s.txt" % stem)).read_text(encoding="utf-8")[:200]
            assert "GENERATED by scripts/lock_toolchain.py" in head, stem
            assert "DO NOT EDIT" in head, stem

    def test_header_is_machine_independent(self):
        # uv stamps its own invocation (absolute paths, the -o target) into a
        # header; lock_toolchain.py strips it. If it leaked back in, the drift
        # check would fail on CI for everything generated on a laptop.
        for stem in GROUPS:
            text = (REQS / ("%s.txt" % stem)).read_text(encoding="utf-8")
            assert "autogenerated by uv" not in text, stem
            assert str(ROOT) not in text, stem


class TestEvalExtraStaysOut:
    def test_langchain_stack_is_not_locked(self):
        # The [eval] extra deliberately pins the old langchain 0.3 stack (ragas
        # 0.2.x needs it). osv-scanner.yml is PR-diff-scoped specifically to
        # avoid tripping on that pin, so materializing it into a committed,
        # scannable lock would re-expose it. See lock_toolchain.py's docstring.
        for stem in GROUPS:
            text = (REQS / ("%s.txt" % stem)).read_text(encoding="utf-8").lower()
            for forbidden in ("langchain", "ragas", "ranx"):
                assert forbidden not in text, \
                    "%s locks the opt-in [eval] stack (%s)" % (stem, forbidden)


class TestCompileIsStable:
    """The compile must reproduce the committed lock, not chase the newest release.

    uv treats an existing `--output-file` as the preferred solution and keeps
    those pins unless a declaration forces a change. Compiling to stdout instead
    re-resolves against the live index, so any upstream release makes the
    committed lock "stale" and reddens `lint` on unrelated PRs with no code
    change — the exact failure mode requirements/lint-tools.in's header warns
    about, and one this gate hit within a day of landing.

    This asserts the mechanism rather than running uv (which needs the network):
    a resolver invoked without an output file to read cannot be stable.
    """

    def test_compile_passes_output_file_so_uv_reads_current_pins(self):
        src = (ROOT / "scripts" / "lock_toolchain.py").read_text(encoding="utf-8")
        assert "--output-file" in src, \
            "compile_group must give uv the committed lock to prefer"

    def test_compile_seeds_the_scratch_file_from_the_committed_lock(self):
        # Copying the committed .txt into the scratch path is what makes uv
        # prefer the existing pins; without the copy the flag achieves nothing.
        src = (ROOT / "scripts" / "lock_toolchain.py").read_text(encoding="utf-8")
        assert "shutil.copyfile(target, scratch)" in src

    def test_upgrade_is_the_only_way_to_re_resolve(self):
        src = (ROOT / "scripts" / "lock_toolchain.py").read_text(encoding="utf-8")
        assert '"--upgrade"' in src
        # --check must never imply --upgrade, or the gate becomes non-deterministic
        assert "--check and --upgrade are exclusive" in src
