# Copyright the boost contributors.
# SPDX-License-Identifier: Apache-2.0
"""Unit tests: the platform-pin guard over the hash-pinned toolchain locks.

Dependabot re-resolves ``requirements/*.txt`` on Linux and commits that
resolution. A non-universal resolve silently **drops every pin whose
environment marker excludes it on the resolving platform** — ``colorama ;
sys_platform == 'win32'`` vanished from three locks in a single scheduled run.
Because the locks install with ``--require-hashes`` on Windows and macOS too, a
dropped pin is not a smaller lock, it is an install failure on the platform that
needed the package: two Windows test legs and the ``metadata`` job died in their
install step, and the error named the step, never the missing package.

``requirements/platform-pins.lock`` is the committed memory of which pins are
marker-gated. These tests cover the parser that builds it, the audit that
compares it against the locks, and the live invariant that the committed tree
agrees with itself.

The audit is deliberately **uv-free and network-free** — unlike
``lock_toolchain.py --check``, which needs both — so it runs here, in `make
lint`, and in CI, and fails naming the package rather than three jobs later.
"""
from __future__ import annotations

import contextlib
import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
REQS = ROOT / "requirements"
SCRIPT = ROOT / "scripts" / "lock_toolchain.py"
MANIFEST = REQS / "platform-pins.lock"
DEPENDABOT = ROOT / ".github" / "dependabot.yml"


def load_lock_toolchain():
    """Import scripts/lock_toolchain.py by path, the way this repo tests scripts/."""
    spec = importlib.util.spec_from_file_location("lock_toolchain_platform_pins",
                                                  SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


MOD = load_lock_toolchain()

# A compiled lock excerpt in uv's real output shape: continuation backslashes,
# indented --hash lines, a provenance comment, and both marker and plain pins.
SAMPLE = """\
# GENERATED by scripts/lock_toolchain.py — DO NOT EDIT.
colorama==0.4.6 ; sys_platform == 'win32' \\
    --hash=sha256:aaaa \\
    --hash=sha256:bbbb
iniconfig==2.3.0 \\
    --hash=sha256:cccc
pytest==8.4.2 ; python_full_version < '3.10' \\
    --hash=sha256:dddd
pytest==9.1.1 ; python_full_version >= '3.10' \\
    --hash=sha256:eeee
"""


class TestMarkerPins:
    """The parser: which lines count as marker-gated, and what is recorded."""

    def test_a_pin_without_a_marker_is_not_recorded(self):
        # Unmarked pins install everywhere, so losing one is a resolution bug
        # the ordinary drift check already catches. This guard is only about
        # the conditional ones.
        assert "iniconfig" not in dict(MOD.marker_pins(SAMPLE))

    def test_a_marker_gated_pin_is_recorded(self):
        assert ("colorama", "sys_platform == 'win32'") in MOD.marker_pins(SAMPLE)

    def test_the_version_is_deliberately_not_recorded(self):
        # THE DESIGN CHOICE: recording versions would make the manifest churn on
        # every routine bump, and a manifest people regenerate reflexively stops
        # being a tripwire. Name + marker changes only when the *shape* of the
        # resolution changes — which is exactly the regression.
        for name, marker in MOD.marker_pins(SAMPLE):
            assert "==" not in name, name
            assert "0.4.6" not in marker

    def test_a_line_continuation_backslash_is_stripped(self):
        # Every uv pin line ends in ` \` before its hash block. Leaving it on
        # would fold a stray backslash into the marker and make every pin look
        # changed the first time the manifest was compared.
        for _name, marker in MOD.marker_pins(SAMPLE):
            assert not marker.endswith("\\"), marker

    def test_hash_and_comment_lines_are_ignored(self):
        names = [n for n, _ in MOD.marker_pins(SAMPLE)]
        assert not any(n.startswith(("#", "-")) for n in names), names

    def test_two_pins_of_one_package_are_distinguished_by_marker(self):
        # SAMPLE is a fixed literal, not the live lock: at the >=3.12 floor
        # test-tools carries pytest ONCE. The parsing rule it pins is what
        # still matters — a guard keyed on name alone would treat losing one
        # of two marker-split pins as no change, and universal resolution can
        # still emit those for platform (not version) markers.
        pytests = [m for n, m in MOD.marker_pins(SAMPLE) if n == "pytest"]
        assert sorted(pytests) == ["python_full_version < '3.10'",
                                   "python_full_version >= '3.10'"]

    def test_extras_survive_in_the_name(self):
        # uv emits `coverage[toml]==…` routinely; dropping the extra would make
        # two genuinely different requirements compare equal.
        pins = MOD.marker_pins(
            "coverage[toml]==7.10.7 ; python_full_version < '3.10'\n")
        assert pins == (("coverage[toml]", "python_full_version < '3.10'"),)

    def test_a_multi_clause_marker_is_kept_whole(self):
        # release-tools' keyring stack carries four-clause markers. Truncating
        # at the first `and` would collapse distinct pins onto one another.
        line = ("pywin32-ctypes==0.2.3 ; platform_machine != 'ppc64le' and "
                "platform_machine != 's390x' and sys_platform == 'win32'\n")
        (_name, marker), = MOD.marker_pins(line)
        assert marker.endswith("sys_platform == 'win32'")
        assert marker.count("and") == 2

    def test_marker_whitespace_is_normalised(self):
        # Same pin, cosmetically different spacing, must not read as a change.
        a = MOD.marker_pins("colorama==0.4.6 ;  sys_platform  ==  'win32'\n")
        b = MOD.marker_pins("colorama==0.4.6 ; sys_platform == 'win32'\n")
        assert a == b


class TestManifestRoundTrip:
    """render → parse must be lossless, and rendering must be deterministic."""

    def test_render_then_parse_round_trips(self):
        locks = {"test-tools": SAMPLE}
        assert MOD.parse_platform_pins(MOD.render_platform_pins(locks)) == {
            "test-tools": MOD.marker_pins(SAMPLE)}

    def test_render_is_deterministic(self):
        locks = {"test-tools": SAMPLE}
        assert MOD.render_platform_pins(locks) == MOD.render_platform_pins(locks)

    def test_the_manifest_is_marked_generated(self):
        head = MANIFEST.read_text(encoding="utf-8")[:400]
        assert "GENERATED by scripts/lock_toolchain.py" in head
        assert "DO NOT EDIT" in head

    def test_the_manifest_is_not_a_requirements_txt(self):
        # test_toolchain_lock.py asserts every requirements/*.txt has a matching
        # .in declaration. A .txt manifest would have none and would fail that
        # gate; the .lock suffix also keeps pip and OSV-Scanner from mistaking
        # this hashless file for something installable.
        assert MANIFEST.suffix == ".lock"
        assert not MANIFEST.with_suffix(".txt").exists()


class TestCommittedTreeIsClean:
    """The live gate: the committed locks must match the committed manifest."""

    def test_the_manifest_exists(self):
        assert MANIFEST.is_file()

    def test_the_committed_locks_match_the_committed_manifest(self):
        problems = MOD.audit_platform_pins(MOD.read_locks(),
                                           MANIFEST.read_text(encoding="utf-8"))
        assert problems == [], "\n".join(problems)

    def test_every_group_is_covered_by_the_manifest(self):
        recorded = MOD.parse_platform_pins(MANIFEST.read_text(encoding="utf-8"))
        for stem, _python_version in MOD.GROUPS:
            assert stem in recorded, stem

    def test_the_windows_pins_that_actually_broke_are_recorded(self):
        # The observed failure, pinned as a fact: colorama is pytest's Windows
        # terminal dependency and pywin32-ctypes is keyring's Windows backend
        # (keyring being twine's own dependency). These are the pins whose loss
        # killed the Windows test legs and the metadata job.
        recorded = MOD.parse_platform_pins(MANIFEST.read_text(encoding="utf-8"))
        for stem in ("test-tools", "coverage-tools", "mutation-tools"):
            names = [n for n, _ in recorded[stem]]
            assert "colorama" in names, stem
        release = [n for n, _ in recorded["release-tools"]]
        assert "pywin32-ctypes" in release
        assert "colorama" in release


class TestTheDependabotRegression:
    """The failure this guard exists for, reproduced against the audit."""

    @staticmethod
    def _without(stem, drop):
        """The committed locks, with `drop` deleted from `stem` — the bug."""
        locks = MOD.read_locks()
        kept = [ln for ln in locks[stem].splitlines(True)
                if not ln.startswith(drop + "==")]
        locks[stem] = "".join(kept)
        return locks

    def test_a_dropped_windows_pin_is_reported(self):
        problems = MOD.audit_platform_pins(
            self._without("test-tools", "colorama"),
            MANIFEST.read_text(encoding="utf-8"))
        assert problems, "a lock that lost colorama must not pass the audit"

    def test_the_report_names_the_package_and_the_group(self):
        # The whole point: the real failure said `install test deps` and never
        # mentioned colorama. This message has to do better.
        blob = "\n".join(MOD.audit_platform_pins(
            self._without("test-tools", "colorama"),
            MANIFEST.read_text(encoding="utf-8")))
        assert "colorama" in blob
        assert "test-tools" in blob

    def test_the_report_explains_the_platform_cause(self):
        blob = "\n".join(MOD.audit_platform_pins(
            self._without("test-tools", "colorama"),
            MANIFEST.read_text(encoding="utf-8"))).lower()
        assert "win32" in blob, "name the marker that was lost"

    def test_a_version_bump_alone_is_not_a_regression(self):
        # The guard must not fire on the routine case, or it gets disabled.
        locks = MOD.read_locks()
        locks["test-tools"] = locks["test-tools"].replace(
            "colorama==0.4.6", "colorama==0.4.7")
        assert MOD.audit_platform_pins(
            locks, MANIFEST.read_text(encoding="utf-8")) == []

    def test_a_narrowed_marker_is_reported(self):
        # Not only deletion: a resolve that keeps the package but loses the
        # win32 branch is the same class of bug.
        locks = MOD.read_locks()
        locks["test-tools"] = locks["test-tools"].replace(
            "colorama==0.4.6 ; sys_platform == 'win32'", "colorama==0.4.6")
        assert MOD.audit_platform_pins(locks,
                                       MANIFEST.read_text(encoding="utf-8"))

    def test_an_unrecorded_new_pin_is_reported_as_a_stale_manifest(self):
        # A legitimately-added conditional dependency should ask for a
        # regenerate, and must NOT be described as a lost pin.
        locks = MOD.read_locks()
        locks["test-tools"] += "newpkg==1.0 ; sys_platform == 'darwin'\n"
        blob = "\n".join(MOD.audit_platform_pins(
            locks, MANIFEST.read_text(encoding="utf-8")))
        assert "newpkg" in blob
        assert "lock_toolchain.py" in blob, "tell the reader how to fix it"

    def test_a_lost_pin_and_a_new_pin_are_described_differently(self):
        # Same drift, opposite meanings: one is a broken install on a platform
        # CI does not resolve on, the other is routine. Collapsing them into one
        # "stale" message is how the original bug stayed invisible.
        manifest = MANIFEST.read_text(encoding="utf-8")
        lost = "\n".join(MOD.audit_platform_pins(
            self._without("test-tools", "colorama"), manifest))
        added = MOD.read_locks()
        added["test-tools"] += "newpkg==1.0 ; sys_platform == 'darwin'\n"
        gained = "\n".join(MOD.audit_platform_pins(added, manifest))
        assert lost != gained


class TestAuditCli:
    """`lock_toolchain.py --audit`: exit codes and the fail-fast wiring."""

    @staticmethod
    def _run(monkeypatch, argv):
        mod = load_lock_toolchain()
        monkeypatch.setattr(mod.sys, "argv", ["lock_toolchain.py", *argv])
        try:
            return mod.main()
        except SystemExit as exc:
            return exc.code

    def test_audit_exits_zero_on_the_committed_tree(self, monkeypatch):
        assert self._run(monkeypatch, ["--audit"]) == 0

    def test_audit_exits_one_on_a_regression(self, monkeypatch):
        mod = load_lock_toolchain()
        monkeypatch.setattr(mod.sys, "argv", ["lock_toolchain.py", "--audit"])
        broken = mod.read_locks()
        broken["test-tools"] = broken["test-tools"].replace(
            "colorama==0.4.6 ; sys_platform == 'win32'", "")
        monkeypatch.setattr(mod, "read_locks", lambda: broken)
        assert mod.main() == 1

    def test_audit_needs_no_uv_and_no_network(self, monkeypatch):
        # If the audit ever reached for uv it would stop being runnable in the
        # unit suite, which is where it catches the bug earliest.
        mod = load_lock_toolchain()
        monkeypatch.setattr(mod.sys, "argv", ["lock_toolchain.py", "--audit"])

        def explode(*_a, **_k):
            raise AssertionError("--audit must not invoke a subprocess")

        monkeypatch.setattr(mod.subprocess, "run", explode)
        assert mod.main() == 0

    def test_check_audits_before_it_resolves(self, monkeypatch):
        # --check needs uv and the network; the audit needs neither. Running the
        # audit first means a lost pin is reported even on a runner that cannot
        # resolve, and reported before a slow five-group compile.
        mod = load_lock_toolchain()
        monkeypatch.setattr(mod.sys, "argv", ["lock_toolchain.py", "--check"])
        broken = mod.read_locks()
        broken["test-tools"] = broken["test-tools"].replace(
            "colorama==0.4.6 ; sys_platform == 'win32'", "")
        monkeypatch.setattr(mod, "read_locks", lambda: broken)

        def explode(*_a, **_k):
            raise AssertionError("--check must audit before invoking uv")

        monkeypatch.setattr(mod.subprocess, "run", explode)
        assert mod.main() == 1

    def test_asking_for_both_runs_both(self, monkeypatch):
        # --audit is the cheaper half of --check, so naming both must not let it
        # short-circuit the drift check the caller also asked for.
        mod = load_lock_toolchain()
        monkeypatch.setattr(mod.sys, "argv",
                            ["lock_toolchain.py", "--check", "--audit"])
        reached = []

        def fake_run(cmd, **_):
            reached.append(cmd)
            raise SystemExit("stop here")

        monkeypatch.setattr(mod.subprocess, "run", fake_run)
        with contextlib.suppress(SystemExit):
            mod.main()
        assert reached, "--check --audit must still reach the drift check"

    def test_audit_is_exclusive_with_regeneration_flags(self, monkeypatch):
        for argv in (["--audit", "--upgrade"], ["--audit", "-P", "twine"]):
            out = self._run(monkeypatch, argv)
            assert "audit" in str(out), argv


class TestDependabotDoesNotRegenerateTheLocks:
    """The config half: Dependabot must stop raising these version bumps.

    Version updates are what regenerate the lock; **security** updates are what
    the entry is actually worth, and `open-pull-requests-limit: 0` disables the
    former while leaving the latter firing. Removing the entry outright would
    give up the security coverage too.
    """

    @staticmethod
    def _requirements_entry():
        """The `/requirements` pip block, with the comments documenting it.

        An entry's comment run sits *above* its `- package-ecosystem:` line, so
        a naive split on that marker files each comment block under the
        preceding entry. Walk back over the comment run to attach it, and stop
        short of the next entry's run.
        """
        lines = DEPENDABOT.read_text(encoding="utf-8").splitlines()
        starts = [i for i, line in enumerate(lines)
                  if line.startswith("  - package-ecosystem:")]
        blocks = []
        for n, start in enumerate(starts):
            top = start
            while top > 0 and lines[top - 1].lstrip().startswith("#"):
                top -= 1
            end = starts[n + 1] if n + 1 < len(starts) else len(lines)
            while end > start and lines[end - 1].lstrip().startswith("#"):
                end -= 1
            blocks.append("\n".join(lines[top:end]))
        matching = [b for b in blocks if "directory: /requirements" in b]
        assert len(matching) == 1, "expected exactly one /requirements entry"
        return matching[0]

    def test_the_requirements_entry_still_exists(self):
        # Deleting it would also drop security updates for the toolchain.
        assert "package-ecosystem: pip" in self._requirements_entry()

    def test_version_updates_are_switched_off(self):
        assert "open-pull-requests-limit: 0" in self._requirements_entry()

    def test_the_reason_is_written_down(self):
        # A bare `0` reads like rate-limiting. The next person needs to know it
        # is deliberate and how a bump is landed instead.
        entry = self._requirements_entry()
        assert "lock_toolchain.py" in entry
        assert "security" in entry.lower()

    def test_the_root_entry_is_left_alone(self):
        # pyproject.toml's extras have no committed lock to corrupt, and
        # narrowing that entry is a different roadmap item — keeping this change
        # to one entry keeps the two branches merging cleanly.
        text = DEPENDABOT.read_text(encoding="utf-8")
        assert "directory: /\n" in text
